### ISSUE TITLE
check (enhance?) and document relative path resolution of paths in config (specially paths in args to specific func)

### ISSUE THREAD

**Issue by marc-portier** [vliz-be-opsci/pysembench#12]
Not entirely clear how relative paths in the yaml config are being resolved.

I suspect: 
- this actually falls under the realm of actual  `function:` sub-tasks service implementations (like pysubyt, sembenc, syncfs) to be responsible in the interpretation of the passed `args:` (not all of them being paths) 
  - these implementations will typically resort resolving relative to the CWD 
  - are advised to make sure to log info the absolute paths they use
- which still leaves the responsibility to sembench to: 
  - document / log / expose that path so endusers know what is going on
  - or possibly change to something sensible for those functions to run in 
    - e.g. from a user point of view a relative path in a sembench config file (yml or json) is naievely considered to be relative to (the parent of) that file
    - see tricks in https://phoenixnap.com/kb/python-change-directory

Additionally we might want to consider doing more fancy stuff allowing for more flexible resolving versus various starting points.
We should only consider this path if multiple such starting points would be meaningful. 
Options to consider:
- the config file (as mentioned)
- the known sembench env folders (input, output, data?)
- other?

If this path is to be pursued:
- we should decide on some way to have these start points be added and declared into some path-notation (e.g. using a pseudo scheme like `sempath:config/«relative path here»`)
- the function-handlers within sembench are probably best suited to do this resolving - a generic sempath-resolver could be created to support in that 
- and maybe the specific implemented service-class can still be instructed / made to expose the names of the keys in `args` that are to be resolved?

**Comment by bulricht** [comment]
New approach will be to pass a list of locations (e.g. home, input, output, resources, ...) when creating a `Sembench` instance:
```python
from pysembench import Sembench

sb = Sembench(
    locations={
        "home":"./examples/resources/sembench_data",
        "input":"./examples/resources/input_data",
    }
)

sb.process()
```
Allowing paths in the yaml config to be resolved via `!resolve`:
```yaml
rdf_production_task:
  func: pysubyt
  args:
    input: !resolve {input}/data.csv 
    output: data.ttl
    template:
      jinja_root: templates
      file_name: data.ttl.j2
    sets:
      countries: country_codes.csv
    mode: no-iteration
    force: true
```
